name: GradeQuery

on:
  schedule:
    - cron:  '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

      - name: Check out code
        uses: actions/checkout@v2
      
      - name: install
        run: |
          pip3 install requests
        
      - name: run
        run: STD_ID=${{ secrets.STD_ID }} PASSWORD=${{ secrets.PASSWORD }} TOKEN=${{ secrets.TOKEN }} PUSH_CHANNEL=${{ secrets.PUSH_CHANNEL }} SHOW_DATA_IN_TITLE=${{ secrets.SHOW_DATA_IN_TITLE }} python3 main.py
      
      - name: update
        run: |
          git config --global user.email "_@_.com"
          git config --global user.name "Brother Sun"
          git add *
          git commit -m "automatic update of records"
          git push origin main
